// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thaiojppvqxfloqwiwow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoYWlvanBwdnF4ZmxvcXdpd293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDYwMjAsImV4cCI6MjA2MzcyMjAyMH0.IZC-jutfdDFk2jeZgP6qZ3pey7y-dZ5vtMs1tzxECUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);